# Site settings
title: Matt Wittmann
email: mcwitt@gmail.com
description: "Matt Wittmann"
baseurl: ""
url: "http://localhost:4000"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments

# For Github-flavored markdown
kramdown:
  input: GFM

